version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - JWT_EXPIRATION=86400000
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - APP_BASE_URL=http://localhost:8080
      - FLOW_API_URL=https://www.flow.cl/api
      - FLOW_SERVICE_PRICE=250000

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: