spring.application.name=cts

spring.datasource.url=jdbc:postgresql://localhost:5432/cts_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false