spring.application.name=cts

spring.datasource.url=jdbc:postgresql://localhost:5432/cts_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=${JWT_EXPIRATION:86400000}

spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

notification.days-before=30

app.base-url=${APP_BASE_URL:http://localhost:8080}

flow.api-key=${FLOW_API_KEY:73F29ABF-2745-4EFF-B61E-5C885LAA2A03}
flow.secret-key=${FLOW_SECRET_KEY:427b3f6793bafe2564ff4478d52053a459d0c0f9}
flow.api-url=${FLOW_API_URL:https://sandbox.flow.cl/api}
flow.service-price=${FLOW_SERVICE_PRICE:250000}